"Все что касается пользователей"///////
"Все что касается пользователей"///////
######
//показать всех
GET http://localhost:3000/users/
Accept: application/json,
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM3MzVlM2JjMjBiYjI0OGJmZDk0OTMiLCJpYXQiOjE2NDc3ODU4MTYsImV4cCI6MTY0ODM5MDYxNn0.lkX_7KFEPaSgcpy5iyTmb8Nc5dawqt_7XqrHUi92aac
####
//создать нового
POST http://localhost:3000/signup/
Content-Type: application/json

{

"name": "admin2",
"email":"admin2@ya.ru",
"password":"123"

}
//Войти в свою учетку
#####
POST http://localhost:3000/signin/
Content-Type: application/json

{

"email":"admin2@ya.ru",
"password":"123"

}




//найти конкретного по айди
###

GET  http://localhost:3000/users/me

######
//изменить данные о себе
PATCH   http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "1",
  "about": "простой парень 5"
}
######
//изменить аватар
PATCH   http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "https://i.pinimg.com/originals/f9/88/3e/f9883ea58fd95d84bfce682a779fdb75.jpg"
}
######


###################################################################

"Все что касается карточек"///////
"Все что касается карточек"///////
#####
//получить все карточки
GET http://localhost:3000/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM3MzVlM2JjMjBiYjI0OGJmZDk0OTMiLCJpYXQiOjE2NDc3ODU4MTYsImV4cCI6MTY0ODM5MDYxNn0.lkX_7KFEPaSgcpy5iyTmb8Nc5dawqt_7XqrHUi92aac
###
//создать карточку
POST http://localhost:3000/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM3MzVlM2JjMjBiYjI0OGJmZDk0OTMiLCJpYXQiOjE2NDc3ODU4MTYsImV4cCI6MTY0ODM5MDYxNn0.lkX_7KFEPaSgcpy5iyTmb8Nc5dawqt_7XqrHUi92aac

{
"name": "new Card3",
"link": "link "

}
###################
//добавить лайк
PUT http://localhost:3000/cards/623737d1be86b23b211e4b19/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM3MzVlM2JjMjBiYjI0OGJmZDk0OTMiLCJpYXQiOjE2NDc3ODU4MTYsImV4cCI6MTY0ODM5MDYxNn0.lkX_7KFEPaSgcpy5iyTmb8Nc5dawqt_7XqrHUi92aac

///убрать лайк
########
DELETE  http://localhost:3000/cards/623737d1be86b23b211e4b19/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM3MzVlM2JjMjBiYjI0OGJmZDk0OTMiLCJpYXQiOjE2NDc3ODU4MTYsImV4cCI6MTY0ODM5MDYxNn0.lkX_7KFEPaSgcpy5iyTmb8Nc5dawqt_7XqrHUi92aac


##################
DELETE    http://localhost:3000/cards/622cbc55e9a90ca20e9c
